type: web
build_command: pip install -r requirements.txt
start_command: gunicorn app:app
environments:
  - name: Istekwallet
    size: free
    healthcheck_path: /
    http_port: 8000
    auto_deploy: true